CREATE TABLE  IF NOT EXISTS AUTHORITY (
   ID  BIGSERIAL NOT NULL,
   NAME VARCHAR(255),
   PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS AUTHORITY ADD CONSTRAINT AUTHORITY_NAME UNIQUE (NAME);



CREATE TABLE  IF NOT EXISTS USERS
(
  id bigint NOT NULL,
  active boolean,
  changed_password boolean,
  confirmation_token character varying(255),
  confirmed boolean,
  date_last_change timestamp without time zone,
  first_name character varying(255) NOT NULL,
  last_name character varying(255) NOT NULL,
  email character varying(255) NOT NULL,
  password character varying(255) NOT NULL,
  register_date timestamp without time zone,
  PRIMARY KEY (id)
  
);

ALTER TABLE IF EXISTS USERS_ ADD CONSTRAINT USER_LOGIN UNIQUE (LOGIN);

CREATE TABLE  IF NOT EXISTS USERS_AUTHORITIES (
   USER_ID INT8 NOT NULL,
   AUTHORITY_ID INT8 NOT NULL,
   PRIMARY KEY (USER_ID, AUTHORITY_ID)
);

ALTER TABLE IF EXISTS USERS_AUTHORITIES ADD CONSTRAINT USERS_AUTHORITIES_AUTHORITY
  FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY;

ALTER TABLE IF EXISTS USERS_AUTHORITIES ADD CONSTRAINT USERS_AUTHORITIES_USER_
  FOREIGN KEY (USER_ID) REFERENCES USERS;
