INSERT INTO SPECIALIZATION(ID, NAME) VALUES (1, 'Dentist');
INSERT INTO SPECIALIZATION(ID, NAME) VALUES (2, 'Ophthalmologist');

INSERT INTO DOCTOR(ID, FIRST_NAME, LAST_NAME, SPECIALIZATION_ID) VALUES (1, 'John', 'Kowalsky', 1);
INSERT INTO DOCTOR(ID, FIRST_NAME, LAST_NAME, SPECIALIZATION_ID) VALUES (2, 'Alice', 'Taylor', 1);

INSERT INTO DOCTOR(ID, FIRST_NAME, LAST_NAME, SPECIALIZATION_ID) VALUES (3, 'Arthur', 'Wilson', 2);
INSERT INTO DOCTOR(ID, FIRST_NAME, LAST_NAME, SPECIALIZATION_ID) VALUES (4, 'Jassmine', 'Craven', 2);

